[users]
    [users.user1]
        name = 'Test17'
        email = 'Test17s@yahoo.com'
        gender = 'male'
        status = 'active'
    [users.user1.todos]
        [users.user1.todos.todos1]
            title = 'Todos17'
            due_on = '2022-02-17T17:00:00'
            status = 'non-pending'