[users]
    [users.user1]
        name = 'Test16ssss'
        email = 'Test16ssss@yahoo.com'
        gender = 'male'
        status = 'active'
        [users.user1.posts]
            [users.user1.posts.post1]
                title = 'Post16s'
                body = 'Body Post16s'
                [users.user1.posts.post1.comments]
                    [users.user1.posts.post1.comments.comments1]
                        name = 'Comment16s'
                        email = 'Comment16semail.com'
                        body = 'body for Comment16s'