[users]
    [users.user1]
        name = 'tom3'
        email = 'tomford22elete23@yahoo.com'
        gender = 'male'
        status = 'active'
        [users.user1.posts]
            [users.user1.posts.post1]
                title = 'best post'
                body = 'best body post'
