[users]
    [users.user1]
        name = 'tom3'
        email = 'tomfordelete23@yahoo.com'
        gender = 'male'
        status = 'active'
        [users.user1.posts]
            [users.user1.posts.post1]
                title = 'best post'
                body = 'best body post'
                [users.user1.posts.post1.comments]
                    [users.user1.posts.post1.comments.comments1]
                        name = 'best comment'
                        email = 'email@email.com'
                        body = 'body for comment'
    [users.user2]
        name = 'joana'
        email = 'joana@yahoo.com'
        gender = 'female'
        status = 'inactive'
    [users.user3]
        name = 'legolas'
        email = 'legolas@lotr.mor'
        gender = 'male'
        status = 'active'
    [users.user4]
        name = 'mary'
        email = 'mary@bloody.com'
        gender = 'female'
        status = 'active'
    [users.user5]
        name = 'john'
        email = 'john@doe.com'
        gender = 'male'
        status = 'inactive'

